name: Semgrep SAST Scan

on:
  push:
    branches: [ "master", "main" ]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
